steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-central2-docker.pkg.dev/word-flow-text-analyzer/word-flow-repo/word-flow:latest",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-central2-docker.pkg.dev/word-flow-text-analyzer/word-flow-repo/word-flow:latest",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "word-flow"
      - "--image"
      - "europe-central2-docker.pkg.dev/word-flow-text-analyzer/word-flow-repo/word-flow:latest"
      - "--region"
      - "europe-central2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--timeout"
      - "300"
      - "--set-env-vars"
      - "DEBUG=False,ALLOWED_HOSTS=*"

images:
  - "europe-central2-docker.pkg.dev/word-flow-text-analyzer/word-flow-repo/word-flow:latest"

options:
  logging: CLOUD_LOGGING_ONLY
