# Generated by Django 5.2.5 on 2025-08-22 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_size', models.BigIntegerField(help_text='Image size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('extracted_text', models.TextField()),
                ('detected_language', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField()),
                ('ocr_engine', models.CharField(max_length=50)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('total_words', models.IntegerField()),
                ('valid_words', models.IntegerField()),
                ('invalid_words', models.IntegerField()),
                ('accuracy_percentage', models.FloatField()),
                ('word_details', models.JSONField(default=list, help_text='Detailed information about each word')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='analyzed_images/')),
            ],
            options={
                'verbose_name': 'Image Analysis Result',
                'verbose_name_plural': 'Image Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_images', models.IntegerField(default=0)),
                ('processed_images', models.IntegerField(default=0)),
                ('successful_images', models.IntegerField(default=0)),
                ('failed_images', models.IntegerField(default=0)),
                ('ocr_engine', models.CharField(max_length=50)),
                ('preprocess_enabled', models.BooleanField(default=True)),
                ('word_validation_enabled', models.BooleanField(default=True)),
                ('overall_accuracy', models.FloatField(blank=True, null=True)),
                ('average_processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image Analysis Session',
                'verbose_name_plural': 'Image Analysis Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
